### ISSUE TITLE
what does the 'gcp' mean?

### ISSUE THREAD

**Issue by zengyang7** [Geoff-Holmes/ABC#1]
Thank you for the code. I just wanna test the ABC-SMC. When i run demoScript1.m, an errors ocurred in 'if isempty(gcp('nocreate')); parpool; end';
Could you tell me what does the function 'gcp' mean? Thank you very much

**Comment by Geoff-Holmes** [comment]
Hello - and thanks for your interest in the code.

'gcp' is to find out if there is an existing parallel pool, if not,
'parpool' opens a default pool.
With parallel computing the code will run much faster.

What version of MATLAB are you using? and,
What is the error message you are getting?
.. in case I can help further.

On 7 May 2016 at 04:40, zengyang7 notifications@github.com wrote:

> Thank you for the code. I just wanna test the ABC-SMC. When i run
> demoScript1.m, an errors ocurred in 'if isempty(gcp('nocreate')); parpool;
> end';
> Could you tell me what does the function 'gcp' mean? Thank you very much
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Geoff-Holmes/ABC/issues/1

## 

Geoffrey R Holmes, Research Associate
Dynamics Research Group
Dept of Mechanical Engineering
The University of Sheffield
Mappin Street
Sheffield
S1 3JD
United Kingdom

email: Geoff.R.Holmes@sheffield.ac.uk Geoff.Holmes@sheffield.ac.uk

Tel:  +44 (0)114 222 7848

**Comment by zengyang7** [comment]
The version of Matlab which i am using is 2013a. The detail of the errors is 'Undefined function 'gcp' for input arguments of type 'char'.'. Can I delete it?

**Comment by ahills60** [comment]
@zengyang7 The parallel function [gcp](http://www.mathworks.com/help/distcomp/gcp.html) (get current pool) was added to MATLAB in R2013b. Several functions are dependent on parallelised code and the removal of gcp may have negative (and unsupported) side effects with the most recent commit. You'd likely need to revert to an earlier commit prior to the parpool updates (e.g. fddf005878730fb216143b49f59c22b2a0161199).

As you're working on an earlier version of MATLAB, please bear in mind that other functions and MATLAB syntax may have different functionality where you may see further errors. If possible, please use a more recent version of MATLAB (e.g. R2014a and above) as earlier versions haven't been tested.
